package server;

public interface SqlQueries {
	static final String LOGIN = "SELECT TYPE FROM USER WHERE ID = ? AND PASSWORD = ?";
	static final String GET_PROF_COURSE = "SELECT ID, NAME, ACTIVE FROM COURSE WHERE PROF_ID = ? ORDER BY ID";
	static final String GET_STUDENT_COURSE = "SELECT C.ID, C.NAME, U.LASTNAME FROM COURSE C JOIN STUDENT_ENROLLMENT SE ON SE.COURSE_ID = C.ID JOIN USER U ON U.ID = C.PROF_ID WHERE SE.STUDENT_ID = ? AND C.ACTIVE = 0b1 ORDER BY C.ID";
	static final String UPDATE_COURSE = "UPDATE COURSE SET ACTIVE = ? WHERE ID = ?";
	static final String CREATE_COURSE = "INSERT INTO COURSE (PROF_ID, NAME, ACTIVE) VALUES (?, ?, ?)";
	static final String GET_ASSIGNMENT = "SELECT ID, TITLE, ACTIVE, DUE_DATE FROM ASSIGNMENT WHERE COURSE_ID = ? ORDER BY DUE_DATE";
	static final String UPDATE_ASSIGNMENT = "UPDATE ASSIGNMENT SET ACTIVE = ? WHERE ID = ?";
	static final String CREATE_ASSIGNMENT = "INSERT INTO ASSIGNMENT (COURSE_ID, TITLE, EXTENSION, ACTIVE, DUE_DATE) VALUES (?, ?, ?, ?, ?)";
	static final String GET_ALL_NAME_STUDENT = "SELECT U.ID, U.FIRSTNAME, U.LASTNAME, CASE WHEN SE.STUDENT_ID IS NULL THEN 0b0 ELSE 0b1 END ENROLLED FROM USER U LEFT JOIN STUDENT_ENROLLMENT SE ON U.ID = SE.STUDENT_ID AND SE.COURSE_ID = ? WHERE U.TYPE = 'S' AND U.LASTNAME = ? ORDER BY U.ID";
	static final String GET_ALL_ID_STUDENT = "SELECT U.ID, U.FIRSTNAME, U.LASTNAME, CASE WHEN SE.STUDENT_ID IS NULL THEN 0b0 ELSE 0b1 END ENROLLED FROM USER U LEFT JOIN STUDENT_ENROLLMENT SE ON U.ID = SE.STUDENT_ID AND SE.COURSE_ID = ? WHERE U.TYPE = 'S' AND U.ID = ? ORDER BY U.ID";
	static final String GET_ALL_STUDENT = "SELECT U.ID, U.FIRSTNAME, U.LASTNAME, CASE WHEN SE.STUDENT_ID IS NULL THEN 0b0 ELSE 0b1 END ENROLLED FROM USER U LEFT JOIN STUDENT_ENROLLMENT SE ON U.ID = SE.STUDENT_ID AND SE.COURSE_ID = ? WHERE U.TYPE = 'S' ORDER BY U.ID";
	static final String GET_ENROLLED_NAME_STUDENT = "SELECT U.ID, U.FIRSTNAME, U.LASTNAME FROM USER U JOIN STUDENT_ENROLLMENT E ON U.ID = E.STUDENT_ID WHERE E.COURSE_ID = ? AND U.LASTNAME = ? ORDER BY U.ID";
	static final String GET_ENROLLED_ID_STUDENT = "SELECT U.ID, U.FIRSTNAME, U.LASTNAME FROM USER U JOIN STUDENT_ENROLLMENT E ON U.ID = E.STUDENT_ID WHERE E.COURSE_ID = ? AND U.ID = ? ORDER BY U.ID";
	static final String GET_ENROLLED_STUDENT = "SELECT U.ID, U.FIRSTNAME, U.LASTNAME FROM USER U JOIN STUDENT_ENROLLMENT E ON U.ID = E.STUDENT_ID WHERE E.COURSE_ID = ? ORDER BY U.ID";
	static final String CREATE_ENROLLEMENT = "INSERT INTO STUDENT_ENROLLMENT (STUDENT_ID, COURSE_ID) SELECT ?, ? FROM STUDENT_ENROLLMENT WHERE NOT EXISTS (SELECT * FROM STUDENT_ENROLLMENT WHERE STUDENT_ID = ? AND COURSE_ID = ?) LIMIT 1";
	static final String DELETE_ENROLLEMENT = "DELETE FROM STUDENT_ENROLLMENT WHERE STUDENT_ID = ? AND COURSE_ID = ?";
	static final String GET_LAST_ID = "SELECT LAST_INSERT_ID()";
}
